source 'https://rubygems.org'

gem 'htmlentities', '4.3.1'                    # ruby 1.8 supported version

group :test do
  gem 'rspec', '3.1.0'
  gem 'rake', '12.3.3'
  gem 'coveralls', '0.7.0', :require => false  # ruby 1.8 supported version
  gem 'timecop', '0.6.1'                       # ruby 1.8 supported version
end
